export { createSalesState, applyStatePatch, SALES_STAGES } from './domain/sales-state.mjs'
export { InMemorySalesSessionStore } from './runtime/session-store.mjs'
export { ProductCatalog } from './tools/product-catalog.mjs'
export { selectSalesOutline } from './strategy/doga.mjs'
export { MockSalesReasoner } from './reasoners/mock-reasoner.mjs'
export { OpenAICompatibleSalesReasoner } from './reasoners/openai-compatible.mjs'
export { SalesBackendAdapter } from './backend/sales-backend.mjs'
