services:
  steel:
    image: ghcr.io/steel-dev/steel-browser@sha256:58fc8f1ed309a647ea7e7a53005b90cb239b8995698d195a261654ac8804974c
    ports:
      - "3000:3000"
      - "9223:9223"
    environment:
      DOMAIN: localhost:3000
      CDP_DOMAIN: localhost:9223
      NODE_ENV: production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    shm_size: "2gb"
